### PR TITLE
Youtube Page

### PR DESCRIPTION
**Pull request by yahir91**
In this project, we built a clone of the youtube page. We had to embed a video and a sidebar with video recommendations with embedded images.

The project is a responsive webpage, the video recommendation sidebar will jump to the bottom of the video description section after the threshold of 1400px width is reached, otherwise it should be displayed at the right of the webpage.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @yahir91 and @e71az :clap: :clap:
#### Good job so far :muscle: . You need to fix the page and try to make it look like the original. especially make: :point_down: 

**_1. The main video and the sidebar recommended videos list to be side by side. Currently, the sidebar recommended videos list section is below the main video._**

**_2. Try to improve the pull request message, it should contain a summary of what you did in the project._**

**_3. The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))_**

**_4. Remove all the comments from the code._**

**_5. Fix the Html validation errors and use this [link](https://validator.w3.org/#validate_by_upload) to check if it passes all the tests before submitting for review._**

**_if you have any doubts or questions contact me on slack._**

### Reviewed by Temitayo Adeleke.

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by eliasecasta** [comment]
Hello Temitayo,


Will give you what we think about the next points:


1.- The side video has a media query which controls the sidebar display, if it is more than 1790px it will go down the video, but the original position is to the right, should we remove the query? Or is there a better way than specifying 1790px? (we know that it is a big number, it is adapted to our screens and maybe that is the problem).


-More than 1790px:
-Less than 1790px:
2.- Will improve it.
3.- We forgot about the readme, we will do it.
4.- We read the "best practices" article mentioned in the project and it mentions that we should comment the code as much as possible, that is why we did it thinking that you might grade the comments (we will remove them otherwise)
5.- The backslash "\" was the only character that seemed to work for us for the assets path, we are getting most of those errors due to that problem, is there a better way? Or how should the path for the assets be? I think that we already tried with forward slash "/" and it didn't work as expected for us. (quick note, Yahir is using Linux and I am using windows, I don't know if there is a problem with the paths because of that)
Thank you very much for your feedback Temitayo, have a nice day!

El 29 de abril de 2020, 16:56, Temitayo Adeleke <notifications@github.com> escribió:






Hi @yahir91 and @e71az 👏 👏
Good job so far 💪 . You need to fix the page and try to make it look like the original. especially make: 👇

1. The main video and the sidebar recommended videos list to be side by side. Currently, the sidebar recommended videos list section is below the main video.

2. Try to improve the pull request message, it should contain a summary of what you did in the project.

3. The project should have a descriptive README.md (screenshot from Pathwright)

4. Remove all the comments from the code.

5. Fix the Html validation errors and use this link to check if it passes all the tests before submitting for review.

if you have any doubts or questions contact me on slack.

Reviewed by Temitayo Adeleke.

**Comment by trekab** [comment]
## Status: Changes Required!
Well done @lekegitrepo and @e71az! :clap: Nice work on positioning the navigation elements :handshake: We, however, have some final touches to consider before we can complete this project;

### Required:
* Fix the [HTML validator](https://validator.w3.org/#validate_by_upload) errors.
* Reduce the whitespace to the leftmost end of the main video. This will make the page look more like the original.
* The search bar and button should be touching and should have the same height. This will also make the page look more like the original.

__Kindly work on the requested changes and submit another code review request!__
_Happy coding!_

**Review by davidmrtz-dev — APPROVED** [review]
### **Status: Approved.** ✅ 
****
### Hi Team. 😄 
****
Great Job 💯 👍  @yahir91 @e71az  You correctly implemented all the required changes.
You can merge this branch and move onto the next project. 🎊 
Happy coding! 😄 💻  
****
**[TSE:  David Elí]** 👨‍💻 
Slack: @ David Eli Martinez Garcia

**Pull request merged**
